### ISSUE TITLE
Spirv-Headers have no tags

### ISSUE THREAD

**Issue by winehub** [KhronosGroup/SPIRV-Headers#89] opened 2019-01-15 17:46 UTC
It would bee good to give spirv-headers  tags otherwise users build inconstant applications.

In this case spriv-headers should be synchronized with spirv-tools.

**Comment by cmarcelo** [comment] 2019-01-17 16:50
Possible duplicate of #76.

**Comment by johnkslang** [comment] 2019-01-18 05:08
Yes, let's just have the one issue.

**Closed by johnkslang** 2019-01-18 05:08 UTC
